# Generated by Django 4.0.6 on 2022-09-15 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paltar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('qiymet', models.CharField(max_length=1000)),
                ('sekil', models.ImageField(upload_to='')),
                ('marka', models.CharField(max_length=200, null=True)),
                ('olcu', models.CharField(max_length=20)),
                ('elcatan', models.BooleanField(default=True)),
                ('musteri', models.ManyToManyField(related_name='musteri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
