# Generated by Django 4.0.6 on 2022-09-17 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paltar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paltar',
            name='musteri',
            field=models.ManyToManyField(related_name='paltar_musteri', to=settings.AUTH_USER_MODEL),
        ),
    ]
