# Generated by Django 4.0.6 on 2022-09-20 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paltar', '0002_alter_paltar_musteri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paltar',
            name='musteri',
            field=models.ManyToManyField(null=True, related_name='paltar_musteri', to=settings.AUTH_USER_MODEL),
        ),
    ]
