# Generated by Django 4.0.6 on 2022-09-22 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paltar', '0003_alter_paltar_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='paltar',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paltar',
            name='musteri',
            field=models.ManyToManyField(blank=True, related_name='paltar_musteri', to=settings.AUTH_USER_MODEL),
        ),
    ]
