# Generated by Django 4.0.6 on 2022-09-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paltar', '0004_paltar_add_date_alter_paltar_musteri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_features', models.TextField(blank=True, null=True)),
                ('product_detail', models.TextField(blank=True, null=True)),
                ('about_brend', models.TextField(blank=True, null=True)),
                ('editor_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paltar',
            name='tesvir',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mehsul_tesviri', to='paltar.description'),
        ),
    ]
