# Generated by Django 4.0.6 on 2022-09-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paltar', '0005_description_paltar_tesvir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paltar',
            name='tesvir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mehsul_tesviri', to='paltar.description'),
        ),
    ]
