# Generated by Django 4.0.6 on 2022-09-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paltar', '0008_alter_paltar_kategoriya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paltar',
            name='kategoriya',
            field=models.ManyToManyField(to='paltar.category'),
        ),
        migrations.AlterField(
            model_name='paltar',
            name='tesvir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paltar.description'),
        ),
    ]
