# Generated by Django 4.0.6 on 2022-09-26 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paltar', '0009_alter_paltar_kategoriya_alter_paltar_tesvir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('model', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=20)),
                ('avaliable', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(to='paltar.category')),
                ('client', models.ManyToManyField(blank=True, related_name='product_client', to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paltar.description')),
            ],
        ),
        migrations.DeleteModel(
            name='Paltar',
        ),
    ]
