# Generated by Django 4.0.6 on 2022-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paltar',
            name='ad',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
