# Generated by Django 4.0.6 on 2022-09-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_paltar_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paltar',
        ),
    ]
