# Generated by Django 4.0.6 on 2022-09-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_delete_paltar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesvir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=200, null=True)),
                ('reng', models.CharField(max_length=200)),
                ('olcu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paltar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('qiymet', models.CharField(max_length=1000)),
                ('sekil', models.ImageField(upload_to='')),
                ('elcatan', models.BooleanField(default=True)),
                ('alici', models.ManyToManyField(related_name='mehsul_musteri', to=settings.AUTH_USER_MODEL)),
                ('tesviri', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paltar_tesviri', to='pages.tesvir')),
            ],
        ),
    ]
