# Generated by Django 4.0.6 on 2022-09-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Paltar',
        ),
        migrations.DeleteModel(
            name='Tesvir',
        ),
    ]
